### ISSUE TITLE
Implement Email notifications for alerts.log output

### ISSUE THREAD

**Issue by 4quarks** [CERN-CERT/pDNSSOC#15]
### Problem
The current system relies on the alerts.log file to feed the SIEM, which is essential for monitoring and incident response. However, it's important to enhance our alerting capabilities to ensure that alerts are promptly communicated to the appropriate stakeholders.

### Proposal
We propose implementing email notifications as an initial step to improve our alerting system. This feature will allow us to receive real-time alerts via email, providing an additional layer of visibility and enabling faster response to critical events.

### Implementation Details
To implement email notifications for alerts, the primary focus will be on migrating the existing Ruby code to the new architecture. This migration will enable us to leverage the enhanced capabilities of the new architecture while maintaining the functionality of the old Ruby code.

**Comment by arvchristos** [comment]
This is functionality that belongs to `pdnssoc-cli` tool. Introduced in CERN-CERT/pdnssoc-cli#1
