### ISSUE TITLE
Reload godnscollector filters using SIGHUP

### ISSUE THREAD

**Issue by arvchristos** [CERN-CERT/pDNSSOC#19]
Currently, when new IOCs are introduced from MISP, we are restarting the `godnscollector` process as it can be seen here:

https://github.com/CERN-CERT/pDNSSOC/blob/main/files/configuration/supervisor/supervisord.conf#L25

I initially proposed a new functionality to reload filters with SIGHUP for go-dnscollector here:

https://github.com/dmachard/go-dnscollector/issues/375

Given that this is now introduced in go-dnscollector, we should test the new functionality and just send a signal instead of restarting the process.

**Comment by 4quarks** [comment]
Issue solved by go-dnscollector and implemented https://github.com/CERN-CERT/pDNSSOC/blob/main/files/configuration/dnscollector/dnscollector.service#L7 so we can close this out.
