### ISSUE TITLE
cron-job not using absolute paths

### ISSUE THREAD

**Issue by DanielGeerts** [CERN-CERT/pDNSSOC#31]
My pdnssoc-logs are fulling up with:
/bin/sh: 1: pdnssoc-cli: not found

This is due to the cron-job template not using absolute paths when calling pdnssoc-cli. If I replace the various "pdnssoc-cli"'s with:
/usr/local/bin/pdnssoc-cli   (which is where the executable is located on my Debian 12.7 machine)
it does work.

**Comment by 4quarks** [comment]
Good catch! Thanks for reporting it. We have updated the cron file [1].
Cheers!

[1] https://github.com/CERN-CERT/pDNSSOC/pull/32
